### ISSUE TITLE
`make test` fails with "No such file or directory" exception in tests/run_tests.py

### ISSUE THREAD

**Issue by nnethercote** [mozilla/j2me.js#1322]
I tried to run the tests with `make test` but I got the following error.
```
python tools/preprocess-1.1.0/lib/preprocess.py -s -D RELEASE=false -D PROFILE=0 -D BENCHMARK=false -D JSR_256=1 -D JSR_179=1 -D VERSION=1427405753 -o config/build.js config/build.js.in
make -C java
make[1]: Entering directory '/home/njn/moz/j2me.js/java'
make[1]: 'classes.jar' is up to date.
make[1]: Leaving directory '/home/njn/moz/j2me.js/java'
make -C tools/jasmin-2.4
make[1]: Entering directory '/home/njn/moz/j2me.js/tools/jasmin-2.4'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/njn/moz/j2me.js/tools/jasmin-2.4'
make -C tests
make[1]: Entering directory '/home/njn/moz/j2me.js/tests'
make[1]: Circular Testlets.java <- Testlets.java dependency dropped.
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/njn/moz/j2me.js/tests'
Building J2ME AOT Compiler
node tools/tsc.js --sourcemap --target ES5 references-jsc.ts -d --out bld/j2me-jsc.js
Building J2ME JSC CLI
node tools/tsc.js --sourcemap --target ES5 jsc.ts --out bld/jsc.js
Compiling ...
js bld/jsc.js -cp java/classes.jar -d -jf java/classes.jar -mff aot-methods.txt > bld/classes.jar.js
Compiled 309 methods OK, 0 failed.
make -C bench
make[1]: Entering directory '/home/njn/moz/j2me.js/bench'
make[1]: 'benchmark.jar' is up to date.
make[1]: Leaving directory '/home/njn/moz/j2me.js/bench'
SLIMERJSLAUNCHER=build_tools/xulrunner/xulrunner tests/runtests.py
Traceback (most recent call last):
  File "tests/runtests.py", line 103, in <module>
    run_test(os.getcwd() + script);
  File "tests/runtests.py", line 73, in run_test
    stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, bufsize=1)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Makefile:75: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by marco-c** [comment]
Maybe https://github.com/mozilla/j2me.js/pull/1323 will fix this.

**Comment by nnethercote** [comment]
Turns out I didn't have casper.js installed. It's not mentioned in the README that casper.js is necessary; it would be nice if it was.

**Comment by mykmelez** [comment]
> Turns out I didn't have casper.js installed. It's not mentioned in the README that casper.js is necessary; it would be nice if it was.

Indeed! I add a mention of it to README.md in #1326.
